/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riverpuzzle;

import java.util.ArrayList;
import java.util.List;
import static riverpuzzle.Controller.leftSide;
import static riverpuzzle.Controller.rightSide;
import static riverpuzzle.JFrame1.boatRiders;

/**
 *
 * @author A B C
 */
public class JFramestory2 extends javax.swing.JFrame {
int countRight=1;
   int countLeft=1;
   boolean fromLeftToRight=true;
   boolean fromRightToLeft=true;
   
    /**
     * Creates new form JFrame2story
     */
    IRiverCrossingController c;

    public void setC(IRiverCrossingController c) {
        this.c = c;
    }
    public JFramestory2() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelstory21 = new riverpuzzle.JPanelstory2();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Add Farmer 40 Kg");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add Farmer 60 Kg");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add Farmer 80 Kg");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Add Farmer 90 Kg");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Right!");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Add Animal 20 Kg");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Left!");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Drop");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Drop");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Drop");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Drop");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Drop");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Save");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelstory21Layout = new javax.swing.GroupLayout(jPanelstory21);
        jPanelstory21.setLayout(jPanelstory21Layout);
        jPanelstory21Layout.setHorizontalGroup(
            jPanelstory21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelstory21Layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addGroup(jPanelstory21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelstory21Layout.createSequentialGroup()
                        .addGroup(jPanelstory21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelstory21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelstory21Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelstory21Layout.createSequentialGroup()
                        .addComponent(jButton13)
                        .addGap(21, 21, 21))))
        );
        jPanelstory21Layout.setVerticalGroup(
            jPanelstory21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelstory21Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanelstory21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addGroup(jPanelstory21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addGap(18, 18, 18)
                .addGroup(jPanelstory21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addGap(38, 38, 38)
                .addGroup(jPanelstory21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11))
                .addGap(28, 28, 28)
                .addGroup(jPanelstory21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanelstory21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton7))
                .addGap(47, 47, 47)
                .addComponent(jButton13)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelstory21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelstory21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
System.out.println(c.isBoatOnTheLeftBank());
        Farmer farmer=new Farmer(40);
        if(c.isBoatOnTheLeftBank()==true){
            boatRiders.add(farmer);
           jPanelstory21.moveFarmer40();
           if(leftSide!=null){
           for(int i=0;i<leftSide.size();i++){
           if(leftSide.get(i)instanceof Farmer){
               leftSide.remove(i);
               break;
           }
           }
           }
        }
        else{
        System.out.println("da5lt b false");
         jPanelstory21.moveFarmerBack40();
         boatRiders.add(farmer);
         if(rightSide!=null){
         for(int i=0;i<rightSide.size();i++){
           if(rightSide.get(i)instanceof Farmer){
              rightSide .remove(i);
              System.out.println("removed");
               break;
           }
           }
         }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
public void printCrossers2(){
jPanelstory21.printCrossers();

}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    Farmer farmer=new Farmer(60);
        if(c.isBoatOnTheLeftBank()==true){
            boatRiders.add(farmer);
           jPanelstory21.moveFarmer60();
           if(leftSide!=null){
           for(int i=0;i<leftSide.size();i++){
           if(leftSide.get(i)instanceof Farmer){
               leftSide.remove(i);
               break;
           }
           }
           }
        }
        else{
        System.out.println("da5lt b false");
         jPanelstory21.moveFarmerBack60();
         boatRiders.add(farmer);
         if(rightSide!=null){
         for(int i=0;i<rightSide.size();i++){
           if(rightSide.get(i)instanceof Farmer){
              rightSide .remove(i);
              System.out.println("removed");
               break;
           }
           }
         }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Farmer farmer=new Farmer(80);
        if(c.isBoatOnTheLeftBank()==true){
            boatRiders.add(farmer);
           jPanelstory21.moveFarmer80();
           if(leftSide!=null){
           for(int i=0;i<leftSide.size();i++){
           if(leftSide.get(i)instanceof Farmer){
               leftSide.remove(i);
               break;
           }
           }
           }
        }
        else{
        System.out.println("da5lt b false");
         jPanelstory21.moveFarmerBack80();
         boatRiders.add(farmer);
         if(rightSide!=null){
         for(int i=0;i<rightSide.size();i++){
           if(rightSide.get(i)instanceof Farmer){
              rightSide .remove(i);
              System.out.println("removed");
               break;
           }
           }
         }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       Farmer farmer=new Farmer(90);
        if(c.isBoatOnTheLeftBank()==true){
            boatRiders.add(farmer);
           jPanelstory21.moveFarmer90();
           if(leftSide!=null){
           for(int i=0;i<leftSide.size();i++){
           if(leftSide.get(i)instanceof Farmer){
               leftSide.remove(i);
               break;
           }
           }
           }
        }
        else{
        System.out.println("da5lt b false");
         jPanelstory21.moveFarmerBack90();
         boatRiders.add(farmer);
         if(rightSide!=null){
         for(int i=0;i<rightSide.size();i++){
           if(rightSide.get(i)instanceof Farmer){
              rightSide .remove(i);
              System.out.println("removed");
               break;
           }
           }
         }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        boolean eshta;
        eshta=c.canMove(boatRiders, true);
        System.out.println(eshta);
        if(eshta==true){
            if(countRight==1){
                if(fromLeftToRight==true){
           jPanelstory21.moveBoat();
           fromLeftToRight=false;
                }
           countRight++;
                   
            }
            else 
            {
                jPanelstory21.moveRight();
                countRight--;
               c.doMove(boatRiders, true);
               fromLeftToRight=true;
            }
            
        }
        System.out.println(boatRiders.size());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Farmer farmer = new Farmer(40);
       System.out.println();
        if(c.isBoatOnTheLeftBank()==true){
        jPanelstory21.moveFarmerBack40();
        leftSide.add(farmer);
        for(int i=0;i<boatRiders.size();i++){
        if(boatRiders.get(i) instanceof Farmer){
        boatRiders.remove(i);
        break;
        }
        }  
       }
       else{
           jPanelstory21.moveFarmer40();
           rightSide.add(farmer);
            for(int i=0;i<boatRiders.size();i++){
        if(boatRiders.get(i) instanceof Farmer){
        boatRiders.remove(i);
        break;
        }
        } 
       }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       Farmer farmer = new Farmer(60);
       System.out.println();
        if(c.isBoatOnTheLeftBank()==true){
        jPanelstory21.moveFarmerBack60();
        leftSide.add(farmer);
        for(int i=0;i<boatRiders.size();i++){
        if(boatRiders.get(i) instanceof Farmer){
        boatRiders.remove(i);
        break;
        }
        }  
       }
       else{
           jPanelstory21.moveFarmer60();
           rightSide.add(farmer);
            for(int i=0;i<boatRiders.size();i++){
        if(boatRiders.get(i) instanceof Farmer){
        boatRiders.remove(i);
        break;
        }
        } 
       }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Farmer farmer = new Farmer(80);
       System.out.println();
        if(c.isBoatOnTheLeftBank()==true){
        jPanelstory21.moveFarmerBack80();
        leftSide.add(farmer);
        for(int i=0;i<boatRiders.size();i++){
        if(boatRiders.get(i) instanceof Farmer){
        boatRiders.remove(i);
        break;
        }
        }  
       }
       else{
           jPanelstory21.moveFarmer80();
           rightSide.add(farmer);
            for(int i=0;i<boatRiders.size();i++){
        if(boatRiders.get(i) instanceof Farmer){
        boatRiders.remove(i);
        break;
        }
        } 
       }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Farmer farmer = new Farmer(90);
       System.out.println();
        if(c.isBoatOnTheLeftBank()==true){
        jPanelstory21.moveFarmerBack90();
        leftSide.add(farmer);
        for(int i=0;i<boatRiders.size();i++){
        if(boatRiders.get(i) instanceof Farmer){
        boatRiders.remove(i);
        break;
        }
        }  
       }
       else{
           jPanelstory21.moveFarmer90();
           rightSide.add(farmer);
            for(int i=0;i<boatRiders.size();i++){
        if(boatRiders.get(i) instanceof Farmer){
        boatRiders.remove(i);
        break;
        }
        } 
       }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        boolean eshta;
        eshta=c.canMove(boatRiders, false);
        System.out.println(eshta);
        System.out.println("Size of boatRiders:"+boatRiders.size());
        if(eshta==true){
           // c.doMove(boatRiders, fromLeftToRight);
            if(countLeft==1){
                if(fromRightToLeft==true){
           jPanelstory21.moveBoatLeft();
                fromRightToLeft=false;
                }
           countLeft++;
                   
            }
            else 
            {
                jPanelstory21.moveLeft();
                countLeft--;
               c.doMove(boatRiders, false);
               fromRightToLeft=true;
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
HerbivoreFactory herb = new HerbivoreFactory();
Herbivore herb1 = herb.getHerbivore("Cow");
        if(c.isBoatOnTheLeftBank()==true){
            boatRiders.add(herb1);
           jPanelstory21.moveSheep();
           if(leftSide!=null){
           for(int i=0;i<leftSide.size();i++){
           if(leftSide.get(i)instanceof Plant ){
               leftSide.remove(i);
               break;
           }
           }
           }
        }
        else{
        //System.out.println("da5lt b false");
        jPanelstory21.moveSheepBack();
         boatRiders.add(herb1);
         if(rightSide!=null){
         for(int i=0;i<rightSide.size();i++){
           if(rightSide.get(i)instanceof Herbivore){
              rightSide .remove(i);
             // System.out.println("removed");
               break;
           }
           }
         }
        }        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
         HerbivoreFactory carn = new HerbivoreFactory();
   Herbivore herb1= carn.getHerbivore("Cow");
        if(c.isBoatOnTheLeftBank()==true){
       jPanelstory21.moveSheepBack();
        leftSide.add(herb1);
        for(int i=0;i<boatRiders.size();i++){
        if(boatRiders.get(i) instanceof Herbivore){
        boatRiders.remove(i);
        break;
        }
        }  
       }
       else{
          jPanelstory21.moveSheep();
           rightSide.add(herb1);
            for(int i=0;i<boatRiders.size();i++){
        if(boatRiders.get(i) instanceof Herbivore){
        boatRiders.remove(i);
        break;
        }
        } 
       }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        c.saveGame();
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private riverpuzzle.JPanelstory2 jPanelstory21;
    // End of variables declaration//GEN-END:variables

    void printCrossers() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
